DROP TABLE IF EXISTS template_marketplace;
DROP TABLE IF EXISTS ai_query_history;
DROP TABLE IF EXISTS api_usage_events;
DROP TRIGGER IF EXISTS audit_events_automation_outbox ON audit_events;
DROP FUNCTION IF EXISTS enqueue_automation_event();
DROP TABLE IF EXISTS automation_runs;
DROP TABLE IF EXISTS automation_events;
DROP TABLE IF EXISTS automation_rules;
ALTER TABLE checklist_items DROP COLUMN IF EXISTS sop_version;
ALTER TABLE checklist_items DROP COLUMN IF EXISTS sop_id;
DROP TABLE IF EXISTS sop_triggers;
DROP TABLE IF EXISTS sop_repository;
ALTER TABLE lessons_learned DROP COLUMN IF EXISTS category;
ALTER TABLE decision_logs DROP COLUMN IF EXISTS related_project_id;
ALTER TABLE decision_logs DROP COLUMN IF EXISTS consequences;
ALTER TABLE decision_logs DROP COLUMN IF EXISTS decision;
ALTER TABLE decision_logs DROP COLUMN IF EXISTS context;
ALTER TABLE decision_logs DROP COLUMN IF EXISTS decision_date;
ALTER TABLE meeting_notes DROP COLUMN IF EXISTS related_project_id;
ALTER TABLE meeting_notes DROP COLUMN IF EXISTS attendees;
DROP TRIGGER IF EXISTS wiki_pages_path_version ON wiki_pages;
DROP FUNCTION IF EXISTS maintain_wiki_page_path();
DROP TABLE IF EXISTS wiki_page_versions;
ALTER TABLE wiki_pages DROP COLUMN IF EXISTS version;
ALTER TABLE wiki_pages DROP COLUMN IF EXISTS path;
