<?php

namespace App\Http\Controllers;

use App\Support\ApiResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class PlatformController extends Controller
{
    use ApiResponse;
    private function u(Request $r):object{return $r->attributes->get('principal');}private function t(Request $r):string{return $this->u($r)->tenant_id;}
    private function rows($q):array{return $q->get()->map(fn($x)=>(array)$x)->all();}private function pg(array $v):string{return '{'.implode(',',array_map(fn($x)=>'"'.str_replace('"','\"',$x).'"',$v)).'}';}
    private function table(string $kind):?string{return ['wiki'=>'wiki_pages','meetings'=>'meeting_notes','decisions'=>'decision_logs','lessons'=>'lessons_learned'][$kind]??null;}
    public function workspaces(Request $r){return $this->ok($r,$this->rows(DB::table('knowledge_workspaces')->where('tenant_id',$this->t($r))->whereNull('deleted_at')->orderBy('name')));}
    public function createWorkspace(Request $r){$d=$r->validate(['name'=>'required','description'=>'nullable|string']);$id=(string)Str::uuid();DB::table('knowledge_workspaces')->insert(['id'=>$id,'tenant_id'=>$this->t($r),'name'=>$d['name'],'description'=>$d['description']??null,'created_at'=>now(),'updated_at'=>now()]);return $this->ok($r,(array)DB::table('knowledge_workspaces')->where('id',$id)->first(),201);}
    public function knowledge(Request $r,string $kind){$type=DB::table('knowledge_types')->where('tenant_id',$this->t($r))->where('slug',$kind)->first();$table=$this->table($kind);if(!$table&&$type)$table='wiki_pages';if(!$table)return $this->fail($r,'NOT_FOUND','knowledge kind not found',404);$q=DB::table($table)->where('tenant_id',$this->t($r))->whereNull('deleted_at');if($table==='wiki_pages'&&$type)$q->where('knowledge_type_id',$type->id);if($r->q)$q->where(fn($x)=>$x->where('title','ilike','%'.$r->q.'%')->orWhere('content','ilike','%'.$r->q.'%'));return $this->ok($r,$this->rows($q->orderByDesc('updated_at')));}
    public function createKnowledge(Request $r,string $kind){$type=DB::table('knowledge_types')->where('tenant_id',$this->t($r))->where('slug',$kind)->first();$table=$this->table($kind);if(!$table&&$type)$table='wiki_pages';if(!$table)return $this->fail($r,'NOT_FOUND','knowledge kind not found',404);$d=$r->validate(['workspace_id'=>'required|uuid','title'=>'required','content'=>'nullable|string','parent_page_id'=>'nullable|uuid','tags'=>'array','knowledge_types'=>'sometimes|array|min:1','knowledge_types.*'=>'string|max:80','external_resources'=>'sometimes|array|max:20','external_resources.*.url'=>'required|url|max:2048','external_resources.*.type'=>'required|in:url,google_docs','external_resources.*.label'=>'nullable|string|max:160','knowledge_source_mode'=>'sometimes|in:internal,external']);$id=(string)Str::uuid();$row=['id'=>$id,'tenant_id'=>$this->t($r),'workspace_id'=>$d['workspace_id'],'title'=>$d['title'],'content'=>$d['content']??'','author_id'=>$this->u($r)->id,'tags'=>$this->pg($d['tags']??[]),'knowledge_types'=>$this->pg($d['knowledge_types']??[$kind]),'external_resources'=>json_encode($d['external_resources']??[]),'knowledge_source_mode'=>$d['knowledge_source_mode']??'internal','created_at'=>now(),'updated_at'=>now()];if($table==='wiki_pages'){$row['parent_page_id']=$d['parent_page_id']??null;$row['knowledge_type_id']=$type?->id;}DB::table($table)->insert($row);return $this->ok($r,(array)DB::table($table)->where('id',$id)->first(),201);}
    public function updateKnowledge(Request $r,string $kind,string $id){$table=$this->table($kind);$d=array_intersect_key($r->all(),array_flip(['title','content','parent_page_id']));if(isset($r->tags))$d['tags']=$this->pg($r->tags);$d['updated_at']=now();DB::table($table)->where('tenant_id',$this->t($r))->where('id',$id)->update($d);return $this->ok($r,(array)DB::table($table)->where('id',$id)->first());}
    public function sops(Request $r){return $this->ok($r,DB::table('sop_repository')->where('tenant_id',$this->t($r))->orderByDesc('updated_at')->get()->map(fn($x)=>['id'=>$x->id,'name'=>$x->title,'version'=>$x->version,'description'=>$x->description])->all());}
    public function createSop(Request $r){$d=$r->validate(['name'=>'required','description'=>'nullable','items'=>'array']);$workspace=DB::table('knowledge_workspaces')->where('tenant_id',$this->t($r))->value('id');if(!$workspace){$workspace=(string)Str::uuid();DB::table('knowledge_workspaces')->insert(['id'=>$workspace,'tenant_id'=>$this->t($r),'name'=>'Operations','created_at'=>now(),'updated_at'=>now()]);}$id=(string)Str::uuid();$steps=array_map(fn($x)=>['label'=>$x],$d['items']??[]);DB::table('sop_repository')->insert(['id'=>$id,'tenant_id'=>$this->t($r),'workspace_id'=>$workspace,'title'=>$d['name'],'description'=>$d['description']??null,'steps'=>json_encode($steps),'version'=>1,'author_id'=>$this->u($r)->id,'is_active'=>true,'created_at'=>now(),'updated_at'=>now()]);return $this->ok($r,['id'=>$id,'name'=>$d['name'],'version'=>1],201);}
    public function rules(Request $r){return $this->ok($r,DB::table('automation_rules')->where('tenant_id',$this->t($r))->get()->map(fn($x)=>['id'=>$x->id,'name'=>$x->name,'event_type'=>$x->trigger_event,'is_active'=>$x->is_active])->all());}
    public function templates(Request $r){return $this->ok($r,$this->rows(DB::table('project_templates')->select('id','name')->where('tenant_id',$this->t($r))->whereNull('deleted_at')->orderBy('name')));}
    public function ask(Request $r){$question=trim((string)$r->question);$projects=DB::table('projects')->where('tenant_id',$this->t($r))->whereNull('deleted_at')->count();$tasks=DB::table('tasks')->where('tenant_id',$this->t($r))->whereNull('deleted_at')->where('board_column','!=','done')->count();$answer="Current workspace has {$projects} projects and {$tasks} open tasks.";$id=(string)Str::uuid();DB::table('ai_query_history')->insert(['id'=>$id,'tenant_id'=>$this->t($r),'user_id'=>$this->u($r)->id,'question'=>$question,'answer'=>$answer,'evidence_json'=>json_encode([]),'created_at'=>now()]);return $this->ok($r,['answer'=>$answer,'evidence'=>[['label'=>'Projects','value'=>$projects,'source'=>'projects'],['label'=>'Open tasks','value'=>$tasks,'source'=>'tasks']]]);}
    public function apiClients(Request $r){return $this->ok($r,DB::table('api_clients')->select('id','name','client_id','scopes','is_active','created_at')->where('tenant_id',$this->t($r))->get()->map(function($x){$x->scopes=is_string($x->scopes)?str_getcsv(trim($x->scopes,'{}')):$x->scopes;return $x;})->all());}
    public function createApiClient(Request $r){$d=$r->validate(['name'=>'required','scopes'=>'array']);$id=(string)Str::uuid();$client='npms_'.Str::lower(Str::random(16));$secret=Str::random(48);DB::table('api_clients')->insert(['id'=>$id,'tenant_id'=>$this->t($r),'name'=>$d['name'],'client_id'=>$client,'client_secret_hash'=>password_hash($secret,PASSWORD_BCRYPT),'scopes'=>$this->pg($d['scopes']??[]),'is_active'=>true,'created_at'=>now(),'updated_at'=>now()]);return $this->ok($r,['id'=>$id,'name'=>$d['name'],'client_id'=>$client,'client_secret'=>$secret,'scopes'=>$d['scopes']??[]],201);}
    public function usage(Request $r){return $this->ok($r,DB::table('api_clients as c')->leftJoin('api_usage_events as u','u.api_client_id','=','c.id')->where('c.tenant_id',$this->t($r))->groupBy('c.id','c.name')->selectRaw('c.name,count(u.id) as requests,count(u.id) filter (where u.status_code>=400) as errors')->get());}
    public function deliveries(Request $r){return $this->ok($r,$this->rows(DB::table('webhook_deliveries')->where('tenant_id',$this->t($r))->orderByDesc('created_at')));}
    public function apiClientHistory(Request $r,string $id){$client=DB::table('api_clients')->where('tenant_id',$this->t($r))->where('id',$id)->first();if(!$client)return $this->fail($r,'NOT_FOUND','API client not found',404);$items=DB::table('api_usage_events')->select('id','request_id','method','path','status_code','duration_ms','occurred_at')->where('tenant_id',$this->t($r))->where('api_client_id',$id)->orderByDesc('occurred_at')->limit(100)->get();return $this->ok($r,['client'=>['id'=>$client->id,'name'=>$client->name,'client_id'=>$client->client_id,'is_active'=>$client->is_active],'requests'=>$items]);}
    public function removeApiClient(Request $r,string $id){if($this->u($r)->role!=='admin')return $this->fail($r,'FORBIDDEN','admin role required',403);$client=DB::table('api_clients')->where('tenant_id',$this->t($r))->where('id',$id)->first();if(!$client)return $this->fail($r,'NOT_FOUND','API client not found',404);DB::transaction(function()use($r,$id,$client){DB::table('api_clients')->where('tenant_id',$this->t($r))->where('id',$id)->update(['is_active'=>false,'updated_at'=>now()]);DB::table('audit_events')->insert(['id'=>(string)Str::uuid(),'tenant_id'=>$this->t($r),'actor_id'=>$this->u($r)->id,'actor_source'=>'user','action'=>'revoke','entity_type'=>'api_client','entity_id'=>$id,'before_json'=>json_encode((array)$client),'after_json'=>json_encode(['is_active'=>false]),'request_id'=>$r->attributes->get('request_id'),'created_at'=>now()]);});return $this->ok($r,['id'=>$id,'removed'=>true,'is_active'=>false]);}}

