import {useMemo,useState} from "react";
import "./api-reference.css";
type Method="GET"|"POST"|"PATCH"|"PUT"|"DELETE";
type Endpoint={method:Method;path:string;summary:string;body?:string;note?:string};
type Group={name:string;description:string;endpoints:Endpoint[]};
const groups:Group[]=[
{name:"Organization",description:"Divisions, teams, leads, users, and controlled roles.",endpoints:[
{method:"GET",path:"/divisions",summary:"List divisions, teams, and division leads"},
{method:"POST",path:"/divisions",summary:"Create a division and optional initial team",body:'{"name":"Engineering","initial_team_name":"Platform","parent_division_id":null}',note:"Requires Idempotency-Key"},
{method:"PUT",path:"/divisions/{id}/leads",summary:"Replace division lead assignments",body:'{"user_ids":["USER_UUID"]}',note:"Admin only"},
{method:"GET",path:"/users",summary:"List tenant users with team and role"},
{method:"POST",path:"/settings/users",summary:"Create user and assign a controlled role",body:'{"name":"Ayu Putri","email":"ayu@example.com","team_id":"TEAM_UUID","role":"manager"}',note:"Roles: admin, manager, supervisor, staff · Requires Idempotency-Key"}]},
{name:"Projects",description:"Create, inspect, update, assign, and submit projects.",endpoints:[
{method:"GET",path:"/projects?team_id={id}",summary:"List projects with optional team filter"},{method:"POST",path:"/projects",summary:"Create a project",body:'{"name":"Website Revamp","team_id":"TEAM_UUID","project_type":"technical","tags":["priority"],"member_ids":[],"reviewer_ids":[]}',note:"Requires Idempotency-Key"},{method:"GET",path:"/projects/{id}",summary:"Get project detail"},{method:"PATCH",path:"/projects/{id}",summary:"Edit project name, status, metadata, type, or tags",body:'{"status":"active","metadata":{"priority":"high"}}'},{method:"POST",path:"/projects/{id}/assign",summary:"Assign project team or task members",body:'{"team_id":"TEAM_UUID"}'},{method:"POST",path:"/projects/{id}/submit-review",summary:"Submit project to configured reviewers"},{method:"GET",path:"/projects/{id}/finish-attachments",summary:"List project completion evidence"},{method:"POST",path:"/projects/{id}/finish-attachments",summary:"Upload completion evidence",note:"multipart/form-data · Requires Idempotency-Key"},{method:"GET",path:"/preliminary-note-templates",summary:"List preliminary note templates"}]},
{name:"Project activities",description:"Activities are represented by tasks with schedule, description, assignee, and board state.",endpoints:[
{method:"GET",path:"/tasks?project_id={id}",summary:"List project activities"},{method:"POST",path:"/tasks",summary:"Create a project activity",body:'{"project_id":"PROJECT_UUID","title":"Kickoff meeting","description":"Prepare agenda","due_date":"2026-08-01","assignee_id":"USER_UUID"}',note:"Requires Idempotency-Key"},{method:"PATCH",path:"/tasks/{id}",summary:"Edit project activity",body:'{"title":"Updated kickoff","description":"Updated notes","due_date":"2026-08-03","assignee_id":"USER_UUID","board_column":"in_progress","position":1}'},{method:"GET",path:"/tasks/{id}/checklist",summary:"List activity checklist"},{method:"POST",path:"/tasks/{id}/checklist",summary:"Add checklist item",body:'{"label":"Confirm attendees"}',note:"Requires Idempotency-Key"},{method:"PATCH",path:"/tasks/{id}/checklist/{item_id}",summary:"Complete or reopen checklist item",body:'{"is_done":true}'}]},
{name:"Reviews & time",description:"Approval workflows and task-level time tracking.",endpoints:[{method:"GET",path:"/reviews",summary:"List reviews"},{method:"POST",path:"/reviews",summary:"Create a review",body:'{"entity_type":"project","entity_id":"PROJECT_UUID","reviewer_id":"USER_UUID"}',note:"Requires Idempotency-Key"},{method:"PATCH",path:"/reviews/{id}",summary:"Approve, reject, or request revision",body:'{"status":"approved","notes":"Ready to publish"}'},{method:"GET",path:"/time-entries",summary:"List time entries"},{method:"POST",path:"/time-entries/start",summary:"Start task timer",body:'{"task_id":"TASK_UUID"}'},{method:"POST",path:"/time-entries/stop",summary:"Stop active timer",body:'{"time_entry_id":"TIME_ENTRY_UUID"}'}]},
{name:"Workspace settings",description:"Tenant-scoped master data used by project forms.",endpoints:[{method:"GET",path:"/settings/project-types",summary:"List built-in and custom project types"},{method:"POST",path:"/settings/project-types",summary:"Create a project type",body:'{"name":"Campaign","color":"#3b9a68"}',note:"Requires Idempotency-Key"},{method:"GET",path:"/settings/project-metadata-fields",summary:"List custom metadata fields"},{method:"POST",path:"/settings/project-metadata-fields",summary:"Create metadata field",body:'{"name":"Budget","key":"budget","type":"number","options":[],"is_required":false}',note:"Requires Idempotency-Key"}]},
{name:"Knowledge & operations",description:"Knowledge, SOP, automation, assistant, and reusable templates.",endpoints:[{method:"GET",path:"/knowledge/workspaces",summary:"List knowledge workspaces"},{method:"POST",path:"/knowledge/workspaces",summary:"Create knowledge workspace",note:"Requires Idempotency-Key"},{method:"GET",path:"/knowledge/{kind}",summary:"List wiki, SOP, or decision records"},{method:"POST",path:"/knowledge/{kind}",summary:"Create knowledge content",note:"Requires Idempotency-Key"},{method:"PATCH",path:"/knowledge/{kind}/{id}",summary:"Update knowledge content"},{method:"GET",path:"/search",summary:"Search workspace knowledge"},{method:"GET",path:"/sops",summary:"List SOPs"},{method:"POST",path:"/sops",summary:"Create SOP",note:"Requires Idempotency-Key"},{method:"GET",path:"/automations/rules",summary:"List automation rules"},{method:"POST",path:"/assistant/query",summary:"Query workspace assistant",body:'{"query":"Show overdue projects"}'},{method:"GET",path:"/templates",summary:"List reusable project templates"}]},
{name:"Integrations & reporting",description:"API clients, webhooks, notifications, external links, and reports.",endpoints:[{method:"GET",path:"/api-clients",summary:"List API clients"},{method:"POST",path:"/api-clients",summary:"Create API client",note:"Secret is returned once · Requires Idempotency-Key"},{method:"GET",path:"/api-clients/usage",summary:"Get API usage metrics"},{method:"GET",path:"/webhooks/subscriptions",summary:"List webhook subscriptions"},{method:"POST",path:"/webhooks/subscriptions",summary:"Create webhook subscription",body:'{"event":"task.completed","target_url":"https://example.com/hook","secret":"SIGNING_SECRET"}',note:"Requires Idempotency-Key"},{method:"DELETE",path:"/webhooks/subscriptions/{id}",summary:"Delete webhook subscription"},{method:"GET",path:"/webhooks/deliveries",summary:"List webhook delivery history"},{method:"GET",path:"/notifications",summary:"List notifications"},{method:"POST",path:"/notifications",summary:"Create notification",note:"Requires Idempotency-Key"},{method:"GET",path:"/reports/productivity",summary:"Get productivity report data"},{method:"GET",path:"/reports/productivity.pdf",summary:"Download productivity PDF"}]}
];
export function ApiReference(){const[query,setQuery]=useState("");const[active,setActive]=useState("All");const[selected,setSelected]=useState<Endpoint|null>(groups[0].endpoints[1]);const visible=useMemo(()=>groups.map(group=>({...group,endpoints:group.endpoints.filter(endpoint=>(active==="All"||active===group.name)&&`${group.name} ${endpoint.method} ${endpoint.path} ${endpoint.summary}`.toLowerCase().includes(query.toLowerCase()))})).filter(group=>group.endpoints.length),[query,active]);return <article className="api-reference"><header><div><h3>Complete API reference</h3><p>{groups.reduce((sum,g)=>sum+g.endpoints.length,0)} endpoints across the Palemo workspace.</p></div><a href="/openapi.yaml" target="_blank" rel="noreferrer">OpenAPI 3.1 ↗</a></header><div className="reference-guide"><strong>Authentication</strong><code>Authorization: Bearer YOUR_API_KEY</code><span>All paths use <b>/api/v1</b>. POST create operations require <b>Idempotency-Key</b>.</span></div><div className="reference-tools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search endpoint, e.g. division or activity…" aria-label="Search API endpoints"/><select value={active} onChange={e=>setActive(e.target.value)} aria-label="Filter API category"><option>All</option>{groups.map(g=><option key={g.name}>{g.name}</option>)}</select></div><div className="reference-layout"><div className="reference-list">{visible.map(group=><section key={group.name}><h4>{group.name}</h4><p>{group.description}</p>{group.endpoints.map(endpoint=><button key={endpoint.method+endpoint.path} className={selected===endpoint?"selected":""} onClick={()=>setSelected(endpoint)}><b className={endpoint.method.toLowerCase()}>{endpoint.method}</b><code>{endpoint.path}</code><span>{endpoint.summary}</span></button>)}</section>)}{!visible.length&&<p className="api-empty">No endpoint matches your search.</p>}</div>{selected&&<EndpointDetail endpoint={selected}/>}</div></article>}
function EndpointDetail({endpoint}:{endpoint:Endpoint}){const[copied,setCopied]=useState(false);const curl=`curl -X ${endpoint.method} \\\n  "https://your-palemo-domain.com/api/v1${endpoint.path}" \\\n  -H "Authorization: Bearer YOUR_API_KEY"${endpoint.method==="POST"?` \\\n  -H "Idempotency-Key: UNIQUE_REQUEST_ID"`:""}${endpoint.body?` \\\n  -H "Content-Type: application/json" \\\n  -d '${endpoint.body}'`:""}`;return <aside className="endpoint-detail"><span className="eyebrow">Endpoint detail</span><div className="endpoint-title"><b className={endpoint.method.toLowerCase()}>{endpoint.method}</b><code>/api/v1{endpoint.path}</code></div><h4>{endpoint.summary}</h4>{endpoint.note&&<p className="endpoint-note">{endpoint.note}</p>}{endpoint.body&&<><h5>Request body</h5><pre><code>{JSON.stringify(JSON.parse(endpoint.body),null,2)}</code></pre></>}<div className="code-heading"><h5>cURL example</h5><button type="button" className={copied?"copied":""} aria-label="Copy cURL example" title="Copy cURL example" onClick={async()=>{await navigator.clipboard.writeText(curl);setCopied(true);window.setTimeout(()=>setCopied(false),1800)}}><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="8" y="8" width="11" height="11" rx="2"/><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2"/></svg><span>{copied?"Copied":"Copy"}</span></button></div><pre><code>{curl}</code></pre><h5>Response envelope</h5><pre><code>{`{\n  "data": { ... },\n  "meta": { "request_id": "uuid" },\n  "errors": null\n}`}</code></pre></aside>}
