import {useEffect,useRef,useState} from "react";
import {useMutation,useQuery} from "@tanstack/react-query";
import Editor from "@toast-ui/editor";
import colorSyntax from "@toast-ui/editor-plugin-color-syntax";
import "@toast-ui/editor/dist/toastui-editor.css";
import "@toast-ui/editor-plugin-color-syntax/dist/toastui-editor-plugin-color-syntax.css";
import "tui-color-picker/dist/tui-color-picker.css";
import "./project-preliminary-notes.css";
import "./project-preliminary-notes-overrides.css";
import "./knowledge-rich-editor.css";

type EditorMode="visual"|"markdown";type EditorPreference={mode:EditorMode};
async function preferenceApi(init?:RequestInit){const response=await fetch("/api/v1/settings/editor-preference",{credentials:"include",...init});const body=await response.json();if(!response.ok)throw new Error(body.errors?.[0]?.message??"Unable to save editor preference");return body.data as EditorPreference}
function persistentTextColorCommand({selectedColor}:{selectedColor?:string},{tr,selection,schema}:any,dispatch:(tr:unknown)=>void){if(!selectedColor)return false;const mark=schema.marks.span.create({htmlAttrs:{style:`color: ${selectedColor}`}});if(selection.empty)tr.addStoredMark(mark);else tr.addMark(selection.from,selection.to,mark);dispatch(tr);return true}
function underlinePlugin(){return {markdownCommands:{underline:(_payload:unknown,{tr,selection,schema}:any,dispatch:(tr:unknown)=>void)=>{const text=selection.content().content.textBetween(0,selection.content().content.size,"\n");tr.replaceSelectionWith(schema.text(`<u>${text}</u>`));dispatch(tr);return true}},wysiwygCommands:{underline:(_payload:unknown,{tr,selection,schema}:any,dispatch:(tr:unknown)=>void)=>{if(selection.empty)return false;const mark=schema.marks.span.create({htmlAttrs:{style:"text-decoration: underline"}});tr.addMark(selection.from,selection.to,mark);dispatch(tr);return true}}}}

const WORD_LIMIT=20000;
export function KnowledgeRichEditor({value,onChange,onRecommendExternal}:{value:string;onChange:(value:string)=>void;onRecommendExternal?:()=>void}){
 const shell=useRef<HTMLDivElement>(null);const host=useRef<HTMLDivElement>(null);const instance=useRef<Editor|null>(null);const onChangeRef=useRef(onChange);onChangeRef.current=onChange;const[mode,setMode]=useState<EditorMode>("visual");const[selectionMenu,setSelectionMenu]=useState({visible:false,left:0,top:0});const[headingMenu,setHeadingMenu]=useState(false);const[showLimitWarning,setShowLimitWarning]=useState(false);const limitDismissed=useRef(false);
 const preference=useQuery({queryKey:["user","editor-preference"],queryFn:()=>preferenceApi()});const savePreference=useMutation({mutationFn:(next:EditorMode)=>preferenceApi({method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:next})})});const ready=!preference.isPending;
 useEffect(()=>{if(!ready||!host.current)return;const initialMode=preference.data?.mode??"visual";setMode(initialMode);const underlineButton=document.createElement("button");underlineButton.type="button";underlineButton.className="editor-underline-control";underlineButton.textContent="U";underlineButton.title="Underline";underlineButton.setAttribute("aria-label","Underline");const editor=new Editor({el:host.current,height:"560px",minHeight:"420px",initialEditType:initialMode==="markdown"?"markdown":"wysiwyg",previewStyle:"tab",initialValue:value||" ",usageStatistics:false,plugins:[colorSyntax,underlinePlugin],toolbarItems:[["heading","bold","italic",{name:"underline",tooltip:"Underline",el:underlineButton}],["hr"],["ul","ol","task","indent","outdent"],["table","link"],["code","codeblock"]]});editor.addCommand("wysiwyg","color",persistentTextColorCommand);underlineButton.addEventListener("click",()=>{editor.exec("underline");editor.focus()});editor.on("change",()=>onChangeRef.current(editor.getMarkdown()));const visualEditor=host.current.querySelector<HTMLElement>(".toastui-editor-ww-container .ProseMirror");const updateSelectionMenu=()=>{const selection=window.getSelection();if(!selection||selection.isCollapsed||!selection.rangeCount||!visualEditor){setSelectionMenu(current=>({...current,visible:false}));return}const range=selection.getRangeAt(0);if(!visualEditor.contains(range.commonAncestorContainer)){setSelectionMenu(current=>({...current,visible:false}));return}const rect=range.getBoundingClientRect();const shellRect=shell.current?.getBoundingClientRect();if(!shellRect)return;setHeadingMenu(false);setSelectionMenu({visible:true,left:Math.max(4,Math.min(rect.left-shellRect.left,shellRect.width-190)),top:Math.max(4,rect.top-shellRect.top-42)})};document.addEventListener("selectionchange",updateSelectionMenu);instance.current=editor;return()=>{document.removeEventListener("selectionchange",updateSelectionMenu);editor.destroy();instance.current=null}},[ready]);
 useEffect(()=>{const editor=instance.current;if(editor&&editor.getMarkdown()!==value)editor.setMarkdown(value||" ",false)},[value]);
 function selectMode(next:EditorMode){if(next===mode)return;setHeadingMenu(false);setMode(next);setSelectionMenu(current=>({...current,visible:false}));(instance.current as any)?.changeMode(next==="markdown"?"markdown":"wysiwyg",true);savePreference.mutate(next)}
 function applyHeading(level:number){instance.current?.exec("heading",{level});setHeadingMenu(false);setSelectionMenu(current=>({...current,visible:false}));instance.current?.focus()}function formatSelection(command:"bold"|"italic"|"underline"|"color"){setHeadingMenu(false);if(command==="color")host.current?.querySelector<HTMLElement>(".toastui-editor-toolbar-icons.color")?.click();else instance.current?.exec(command);setSelectionMenu(current=>({...current,visible:false}));instance.current?.focus()}
 const wordCount=value.replace(/<[^>]*>/g," ").replace(/[#*_>`~\[\]()-]/g," ").trim().split(/\s+/).filter(Boolean).length;
 useEffect(()=>{if(wordCount>WORD_LIMIT&&!limitDismissed.current)setShowLimitWarning(true);if(wordCount<=WORD_LIMIT){limitDismissed.current=false;setShowLimitWarning(false)}},[wordCount]);
 if(!ready)return <div className="knowledge-editor-loading">Loading editor preference...</div>;
 return <div ref={shell} className="knowledge-editor-shell"><div ref={host} className="toast-editor-host knowledge-rich-editor" aria-label="Knowledge content editor"/>{selectionMenu.visible&&mode==="visual"&&<div className="selection-format-menu knowledge-selection-menu" role="toolbar" aria-label="Text formatting" style={{left:selectionMenu.left,top:selectionMenu.top}} onMouseDown={event=>event.preventDefault()}><div className="selection-heading-picker"><button type="button" aria-label="Choose heading" title="Choose heading" aria-expanded={headingMenu} onClick={()=>setHeadingMenu(open=>!open)}>H</button>{headingMenu&&<div className="selection-heading-options"><button type="button" onClick={()=>applyHeading(1)}>H1</button><button type="button" onClick={()=>applyHeading(2)}>H2</button><button type="button" onClick={()=>applyHeading(3)}>H3</button><button type="button" onClick={()=>applyHeading(0)}>Paragraph</button></div>}</div><button type="button" aria-label="Bold" title="Bold" onClick={()=>formatSelection("bold")}><b>B</b></button><button type="button" aria-label="Italic" title="Italic" onClick={()=>formatSelection("italic")}><i>I</i></button><button type="button" aria-label="Underline" title="Underline" onClick={()=>formatSelection("underline")}><u>U</u></button><button type="button" aria-label="Text color" title="Text color" onClick={()=>formatSelection("color")}>A</button></div>}{showLimitWarning&&<div className="knowledge-word-limit-backdrop"><section className="knowledge-word-limit-dialog" role="dialog" aria-modal="true" aria-labelledby="knowledge-word-limit-title"><span>Editor performance</span><h3 id="knowledge-word-limit-title">This Knowledge is over 20,000 words</h3><p>Large internal documents may become slower while typing or switching editor modes. Consider maintaining the content externally and linking it as a resource.</p><div><button type="button" onClick={()=>{limitDismissed.current=true;setShowLimitWarning(false)}}>Keep editing</button><button type="button" className="use-external" onClick={()=>{setShowLimitWarning(false);onRecommendExternal?.()}}>Use External Resource</button></div></section></div>}<div className="knowledge-editor-tabs" role="tablist" aria-label="Editor mode"><span className={`knowledge-word-count ${wordCount>WORD_LIMIT?"over-limit":""}`}><b>{wordCount.toLocaleString()}</b> words / {WORD_LIMIT.toLocaleString()} words <em>(editor may be delayed)</em></span><button type="button" role="tab" aria-selected={mode==="visual"} className={mode==="visual"?"active":""} onClick={()=>selectMode("visual")}>Visual</button><button type="button" role="tab" aria-selected={mode==="markdown"} className={mode==="markdown"?"active":""} onClick={()=>selectMode("markdown")}>Markdown</button></div></div>;
}