import { FormEvent, useEffect, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import "./project-activity-realization.css";

type Task={id:string;title:string;description?:string;due_date?:string|null;created_at:string;board_column?:string};
type Note={id:string;content_markdown:string;occurred_at:string}; type Realization={task_id:string;realized_date:string|null}; type Envelope<T>={data:T;errors:null|Array<{message:string}>};
async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(path,{credentials:"include",...init});const body=await response.json() as Envelope<T>;if(!response.ok)throw new Error(body.errors?.[0]?.message??"Request failed");return body.data}

export function ProjectActivityRealization({projectID}:{projectID:string}){
 const tasks=useQuery({queryKey:["tasks",projectID,"realization-view"],queryFn:()=>api<Task[]>(`/api/v1/tasks?project_id=${encodeURIComponent(projectID)}`),enabled:!!projectID});
 const [selected,setSelected]=useState<Task|null>(null);const [tab,setTab]=useState<"planned"|"realization">("realization");const [notes,setNotes]=useState<Note[]>([]);const [realizations,setRealizations]=useState<Record<string,string|null>>({});const [date,setDate]=useState("");const [note,setNote]=useState("");const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{if(!selected)return;let cancelled=false;setLoading(true);setError("");Promise.all([api<Note[]>(`/api/v1/tasks/${selected.id}/notes`),api<Realization>(`/api/v1/tasks/${selected.id}/realization`)]).then(([loadedNotes,loaded])=>{if(cancelled)return;setNotes(loadedNotes);setRealizations(current=>({...current,[selected.id]:loaded.realized_date}));setDate(loaded.realized_date??"")}).catch(reason=>{if(!cancelled)setError(reason instanceof Error?reason.message:"Unable to load realization")}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[selected]);
 function open(task:Task){setSelected(task);setTab("realization");setNotes([]);setDate(realizations[task.id]??"");setNote("")}
 async function saveDate(){if(!selected||saving)return;setSaving(true);setError("");try{const next=await api<Realization>(`/api/v1/tasks/${selected.id}/realization`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({realized_date:date||null})});setRealizations(current=>({...current,[selected.id]:next.realized_date}));}catch(reason){setError(reason instanceof Error?reason.message:"Unable to save realization date")}finally{setSaving(false)}}
 async function addNote(event:FormEvent){event.preventDefault();if(!selected||!note.trim()||saving)return;setSaving(true);setError("");try{const created=await api<Note>(`/api/v1/tasks/${selected.id}/notes`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({content_markdown:note.trim(),occurred_at:date||undefined})});setNotes(current=>[created,...current]);setNote("")}catch(reason){setError(reason instanceof Error?reason.message:"Unable to save note")}finally{setSaving(false)}}
 const items=tasks.data??[];const realizedCount=Object.values(realizations).filter(Boolean).length;return <section className="project-realization panel"><header className="project-realization-head"><div><span className="eyebrow">Execution</span><h2>Activity realization</h2><p>Rencana tetap menjadi referensi. Catat tanggal dan realisasi tanpa mengubah planned activity.</p></div><span>{realizedCount} realized</span></header>{tasks.isPending&&<div className="empty-state">Loading activities...</div>}{!tasks.isPending&&items.length===0&&<div className="empty-state">No activities yet.</div>}{items.length>0&&<div className="realization-layout"><div className="realization-activity-list">{items.map(item=>{const realized=!!realizations[item.id];return <button type="button" key={item.id} className={selected?.id===item.id?"active":""} onClick={()=>open(item)}><span className={realized?"realized-icon":"activity-icon"}>{realized?"✓":"•"}</span><span><strong>{item.title}</strong><small>Planned: {item.due_date??item.created_at.slice(0,10)}</small></span></button>})}</div><div className="realization-detail">{!selected&&<div className="empty-state">Select an activity. Realization opens by default.</div>}{selected&&<><div className="realization-tabs"><button type="button" className={tab==="planned"?"active":""} onClick={()=>setTab("planned")}>Planned</button><button type="button" className={tab==="realization"?"active":""} onClick={()=>setTab("realization")}>Realization</button></div>{loading&&<div className="empty-state">Loading activity details...</div>}{!loading&&tab==="planned"&&<div className="planned-readonly"><h3>{selected.title}</h3><dl><dt>Planned date</dt><dd>{selected.due_date??selected.created_at.slice(0,10)}</dd><dt>Planned description</dt><dd>{selected.description||"No description"}</dd><dt>Status</dt><dd>{selected.board_column??"todo"}</dd></dl><small>Planned data is read-only in Project Detail.</small></div>}{!loading&&tab==="realization"&&<div className="realization-form"><label>Realization date<input type="date" value={date} onChange={event=>setDate(event.target.value)} /><small>This date is separate from the planned date.</small></label><button type="button" className="save-realization" disabled={saving} onClick={saveDate}>{saving?"Saving...":"Save realization date"}</button><div className="realization-notes"><h3>Realization notes</h3>{notes.length===0&&<small>No realization notes yet.</small>}{notes.map(item=><article key={item.id}><p>{item.content_markdown}</p><time>{new Date(item.occurred_at).toLocaleString()}</time></article>)}</div><form onSubmit={addNote}><textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Catatan pelaksanaan, hasil, atau kendala..." maxLength={20000}/><button type="submit" className="save-realization" disabled={saving||!note.trim()}>{saving?"Saving...":"Add realization note"}</button></form></div>}{error&&<p className="activity-sync-error">{error}</p>}</>}</div></div>}</section>
}
