import {FormEvent,useEffect,useMemo,useRef,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import type {DivisionPerformanceData} from "./DivisionPerformance";
import {TagMultiSelect} from "./TagMultiSelect";
import {ActivityCalendar,activityTitle,type PlannedActivity} from "./ActivityCalendar";
import {ProjectPreliminaryNotes,type PreliminaryNoteTemplate} from "./ProjectPreliminaryNotes";
import {ProjectTypeSelector,type ProjectTypeOption} from "./ProjectTypeSelector";
import type {MetadataField} from "./SettingsPage";
import {CustomTagInput} from "./CustomTagInput";
import "./project-create.css";
import "./project-form-typography.css";

type User={id:string;name:string;email:string;role:string;team_id?:string};type Project={id:string;name:string;team_id:string;project_type?:string;tags?:string[];preliminary_note_template_id?:string|null;preliminary_notes?:string;preliminary_reviewer_notes?:string;source?:string|null;source_ref?:string|null;metadata?:{finish_date?:string;notes?:string|null;preliminary_knowledge_id?:string|null;project_scope?:{division_ids?:string[];team_ids?:string[];user_ids?:string[]};custom_fields?:Record<string,string|boolean>;knowledge_page_ids?:string[]};member_ids?:string[];reviewer_ids?:string[]};type Task={id:string;title:string;description:string;board_column:"todo"|"in_progress"|"review"|"done";due_date?:string|null;created_at:string};type KnowledgePage={id:string;title:string;workspace_id:string;tags:string[]};type Envelope<T>={data:T;errors:null|Array<{message:string}>};
type ExistingProject={id:string;tags?:string[]};
async function api<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(path,{credentials:"include",...init});const body=await response.json() as Envelope<T>;if(!response.ok)throw new Error(body.errors?.[0]?.message??"Request failed");return body.data}

export function ProjectCreateForm({divisions,projectID,onCreated,onCancel}:{divisions:DivisionPerformanceData[];projectID?:string;onCreated:(id:string)=>void;onCancel:()=>void}){
 const cache=useQueryClient();const initialized=useRef("");const editing=!!projectID;const[name,setName]=useState("");const[activities,setActivities]=useState<PlannedActivity[]>([]);const[finishDate,setFinishDate]=useState("");const[preliminaryTemplateID,setPreliminaryTemplateID]=useState("");const[preliminaryNotes,setPreliminaryNotes]=useState("");const[preliminaryReviewerNotes,setPreliminaryReviewerNotes]=useState("");const[projectType,setProjectType]=useState("operational");const[metadataValues,setMetadataValues]=useState<Record<string,string|boolean>>({});const[tags,setTags]=useState<string[]>([]);const[notes,setNotes]=useState("");const[source,setSource]=useState("");const[sourceRef,setSourceRef]=useState("");const[knowledgePageIDs,setKnowledgePageIDs]=useState<string[]>([]);const[projectScopes,setProjectScopes]=useState<string[]>([]);const[reviewerIDs,setReviewerIDs]=useState<string[]>([]);
 const teams=divisions.flatMap(division=>(division.teams??[]).map(team=>({...team,divisionName:division.name})));
 const users=useQuery({queryKey:["users"],queryFn:()=>api<User[]>("/api/v1/users")});const currentUser=useQuery({queryKey:["current-user"],queryFn:()=>api<User>("/api/v1/auth/me")});const preliminaryTemplates=useQuery({queryKey:["preliminary-note-templates"],queryFn:()=>api<PreliminaryNoteTemplate[]>("/api/v1/preliminary-note-templates")});const knowledge=useQuery({queryKey:["knowledge","wiki"],queryFn:()=>api<KnowledgePage[]>("/api/v1/knowledge/wiki")});const projectTypes=useQuery({queryKey:["settings","project-types"],queryFn:()=>api<ProjectTypeOption[]>("/api/v1/settings/project-types")});const metadataFields=useQuery({queryKey:["settings","metadata-fields"],queryFn:()=>api<MetadataField[]>("/api/v1/settings/project-metadata-fields")});
 const existingProjects=useQuery({queryKey:["projects"],queryFn:()=>api<ExistingProject[]>("/api/v1/projects")});const editingProject=useQuery({queryKey:["project",projectID],queryFn:()=>api<Project>(`/api/v1/projects/${projectID}`),enabled:editing});const editingTasks=useQuery({queryKey:["tasks",projectID],queryFn:()=>api<Task[]>(`/api/v1/tasks?project_id=${projectID}`),enabled:editing});useEffect(()=>{const project=editingProject.data;if(!editing||!project||!editingTasks.data||initialized.current===project.id)return;initialized.current=project.id;const metadata=project.metadata??{};const scope=metadata.project_scope??{};setName(project.name);setProjectType(project.project_type??"operational");setTags(project.tags??[]);setPreliminaryTemplateID(metadata.preliminary_knowledge_id?`knowledge:${metadata.preliminary_knowledge_id}`:project.preliminary_note_template_id??"");setPreliminaryNotes(project.preliminary_notes??"");setPreliminaryReviewerNotes(project.preliminary_reviewer_notes??"");setFinishDate(metadata.finish_date??"");setNotes(metadata.notes??"");setMetadataValues(metadata.custom_fields??{});setKnowledgePageIDs(metadata.knowledge_page_ids??[]);setSource(project.source??"");setSourceRef(project.source_ref??"");setReviewerIDs(project.reviewer_ids??[]);const scopes=[...(scope.division_ids??[]).map(id=>`division:${id}`),...(scope.team_ids??[]).map(id=>`team:${id}`),...(scope.user_ids??project.member_ids??[]).map(id=>`user:${id}`)];setProjectScopes(scopes.length?scopes:[`team:${project.team_id}`]);setActivities(editingTasks.data.map(task=>({id:task.id,date:(task.due_date??task.created_at).slice(0,10),title:task.title,description:task.description||task.title,boardColumn:task.board_column})))},[editing,editingProject.data,editingTasks.data]);
 const canEditReviewerNote=!!editing&&!!currentUser.data?.id&&!!editingProject.data?.reviewer_ids?.includes(currentUser.data.id);
 const scopeOptions=[...divisions.map(division=>({value:`division:${division.id}`,label:division.name,description:"Division · includes its teams",tone:"division" as const})),...teams.map(team=>({value:`team:${team.id}`,label:team.name,description:`Team · ${team.divisionName}`,tone:"team" as const})),...(users.data??[]).map(user=>({value:`user:${user.id}`,label:user.name,description:`User · ${user.role} · ${user.email}`,tone:"user" as const}))];
 const selectedTeamScope=projectScopes.find(value=>value.startsWith("team:"))?.slice(5);const teamID=selectedTeamScope??divisions.find(division=>projectScopes.includes(`division:${division.id}`)&&!!division.teams?.length)?.teams[0].id??(users.data??[]).find(user=>!!user.team_id&&projectScopes.includes(`user:${user.id}`))?.team_id??"";
 const explicitMemberIDs=projectScopes.filter(value=>value.startsWith("user:")).map(value=>value.slice(5));const projectScopeMetadata={division_ids:projectScopes.filter(value=>value.startsWith("division:")).map(value=>value.slice(9)),team_ids:projectScopes.filter(value=>value.startsWith("team:")).map(value=>value.slice(5)),user_ids:explicitMemberIDs};
 const popularTags=useMemo(()=>{const counts=new Map<string,{tag:string;count:number}>();for(const project of existingProjects.data??[]){for(const tag of project.tags??[]){const key=tag.toLocaleLowerCase();const current=counts.get(key);counts.set(key,{tag:current?.tag??tag,count:(current?.count??0)+1})}}return [...counts.values()].sort((a,b)=>b.count-a.count||a.tag.localeCompare(b.tag))},[existingProjects.data]);
 const missingRequirements=[...(!name.trim()?["Project name"]:[]),...(!projectScopes.length?["Scope & Members"]:[]),...((projectScopes.length&&!teamID)?["A scope with an available team"]:[]),...(!finishDate?["Finish date"]:[]),...(metadataFields.data??[]).filter(field=>field.is_required&&(metadataValues[field.key]===undefined||metadataValues[field.key]==="")).map(field=>field.name)];
 const save=useMutation({mutationFn:async()=>{const payload={name:name.trim(),team_id:teamID,project_type:projectType,tags,preliminary_note_template_id:preliminaryTemplateID&&!preliminaryTemplateID.startsWith("knowledge:")?preliminaryTemplateID:null,preliminary_notes:preliminaryNotes,...(editing&&canEditReviewerNote?{preliminary_reviewer_notes:preliminaryReviewerNotes}:{}),knowledge_page_ids:knowledgePageIDs,member_ids:explicitMemberIDs,reviewer_ids:reviewerIDs,source:source.trim()||null,source_ref:sourceRef.trim()||null,metadata:{created_from:"project_portfolio",finish_date:finishDate||null,notes:notes.trim()||null,preliminary_knowledge_id:preliminaryTemplateID.startsWith("knowledge:")?preliminaryTemplateID.slice(10):null,project_scope:projectScopeMetadata,custom_fields:metadataValues,knowledge_page_ids:knowledgePageIDs}};const project=editing?await api<Project>(`/api/v1/projects/${projectID}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}):await api<Project>("/api/v1/projects",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(payload)});const previous=new Map((editingTasks.data??[]).map(task=>[task.id,task]));const nextIDs=new Set(activities.map(activity=>activity.id));const requests:Promise<unknown>[]=[];if(editing)for(const task of editingTasks.data??[])if(!nextIDs.has(task.id))requests.push(api(`/api/v1/tasks/${task.id}`,{method:"DELETE"}));for(const[position,activity]of activities.entries()){const task=previous.get(activity.id);const taskPayload={title:activityTitle(activity.description),description:activity.description,due_date:`${activity.date}T23:59:59Z`,board_column:activity.boardColumn??"todo",position};if(task)requests.push(api(`/api/v1/tasks/${task.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(taskPayload)}));else requests.push(api<Task>("/api/v1/tasks",{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({...taskPayload,project_id:project.id,assignee_id:null})}));}await Promise.all(requests);return project},onSuccess:project=>{cache.invalidateQueries({queryKey:["projects"]});cache.invalidateQueries({queryKey:["project",project.id]});cache.invalidateQueries({queryKey:["tasks",project.id]});cache.invalidateQueries({queryKey:["dashboard-summary"]});onCreated(project.id)}}); function submit(e:FormEvent){e.preventDefault();if(!missingRequirements.length)save.mutate()}
 if(editing&&(editingProject.isPending||editingTasks.isPending))return <section className="project-create-card"><div className="create-form-head"><div><span className="eyebrow">Edit project</span><h3>Loading project workspace...</h3><p>Preparing the existing project data and activities.</p></div></div></section>;
 return <section className="project-create-card"><div className="create-form-head"><div><span className="eyebrow">{editing?"Edit project":"New project"}</span><input className="project-heading-title-input" autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Untitled project" maxLength={160} aria-label="Project title"/></div><button type="button" onClick={onCancel} aria-label="Close project form">x</button></div><form onSubmit={submit} className="project-create-layout">
  <div className="project-main-column">
   <div className="activity-builder"><div className="activity-head"><div><span>Project activities</span><small>Switch between Calendar, Tree, and Kanban modes. All views share the same activities.</small></div><div className="calendar-legend"><span className="legend-today">Today</span><span className="legend-activity">Activity</span><span className="legend-finish">Finish</span></div></div><ActivityCalendar activities={activities} onActivitiesChange={setActivities} finishDate={finishDate} onFinishDateChange={setFinishDate} reviewerCount={reviewerIDs.length} periodViews/></div>
   <ProjectPreliminaryNotes value={preliminaryNotes} onChange={setPreliminaryNotes} reviewerValue={preliminaryReviewerNotes} onReviewerChange={setPreliminaryReviewerNotes} canEditReviewerNote={canEditReviewerNote} templates={preliminaryTemplates.data??[]} selectedKnowledgeIDs={knowledgePageIDs} onKnowledgeIDsChange={setKnowledgePageIDs}/>

  </div>
  <aside className="project-settings-column"><label><span>Scope & Members</span><TagMultiSelect options={scopeOptions} value={projectScopes} onChange={setProjectScopes} placeholder="Select divisions, teams, or specific users"/><small>One field for project-wide divisions, teams, and individual members.</small></label>
   <ProjectTypeSelector value={projectType} onChange={setProjectType} options={projectTypes.data??[]}/>
   {!!metadataFields.data?.length&&<div className="dynamic-metadata-fields"><strong>Project metadata</strong>{metadataFields.data.map(field=><DynamicMetadataField key={field.id} field={field} value={metadataValues[field.key]} onChange={value=>setMetadataValues(current=>({...current,[field.key]:value}))}/>)}</div>}
   <label><span>Project tags</span><CustomTagInput value={tags} onChange={setTags} popularTags={popularTags}/><small>Add labels for filtering and project discovery.</small></label>
   <label><span>Reviewers</span><TagMultiSelect options={(users.data??[]).filter(user=>!explicitMemberIDs.includes(user.id)).map(user=>({value:user.id,label:user.name,description:`${user.role} - ${user.email}`}))} value={reviewerIDs} onChange={setReviewerIDs} placeholder="Optional reviewers"/><small>If empty, Finish completes the project directly.</small></label><label><span>Linked knowledge pages</span><TagMultiSelect options={(knowledge.data??[]).map(page=>({value:page.id,label:page.title,description:Array.isArray(page.tags)?page.tags.join(", "):"Wiki page"}))} value={knowledgePageIDs} onChange={setKnowledgePageIDs} placeholder={knowledge.isLoading?"Loading...":"Select pages"}/></label>
   <label><span>Notes</span><textarea rows={5} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Project context, constraints, or management notes"/></label>
   <details><summary>Additional information</summary><div className="additional-fields"><label><span>External source</span><input value={source} onChange={e=>setSource(e.target.value)} placeholder="e.g. woocommerce"/></label><label><span>Reference ID</span><input value={sourceRef} onChange={e=>setSourceRef(e.target.value)} placeholder="e.g. order-1042"/></label></div></details>
  </aside>
  {!!missingRequirements.length&&<div className="project-requirements"><strong>{editing?"Complete the following before saving this project:":"Complete the following before creating this project:"}</strong><ul>{missingRequirements.map(item=><li key={item}>{item}</li>)}</ul></div>}{save.isError&&<p className="form-error layout-error">{save.error.message}</p>}<div className="form-actions layout-actions"><button type="button" onClick={onCancel}>Cancel</button><button className="create-submit" disabled={save.isPending||!!missingRequirements.length}>{save.isPending?(editing?"Saving...":"Creating..."):(editing?"Save changes":"Create project")}</button></div>
 </form></section>
}

function DynamicMetadataField({field,value,onChange}:{field:MetadataField;value:string|boolean|undefined;onChange:(value:string|boolean)=>void}){if(field.type==="boolean")return <label className="metadata-checkbox"><input type="checkbox" checked={value===true} onChange={e=>onChange(e.target.checked)}/><span>{field.name}{field.is_required?" *":""}</span></label>;return <label><span>{field.name}{field.is_required?" *":""}</span>{field.type==="select"?<select value={String(value??"")} onChange={e=>onChange(e.target.value)} required={field.is_required}><option value="">Select {field.name}</option>{(field.options??[]).map(option=><option key={option} value={option}>{option}</option>)}</select>:<input type={field.type} value={String(value??"")} onChange={e=>onChange(e.target.value)} required={field.is_required}/>}</label>}






